import { ItemDetail } from './itemdetail';

export const MOCKDATA: ItemDetail[] = [
    // Category 1 - Types
    { id: 1, name: 'Book', categoryId: 1 },
    { id: 2, name: 'Roleplaying Game', categoryId: 1 },
    { id: 3, name: 'Movie', categoryId: 1 },
    { id: 4, name: 'Video Game', categoryId: 1 },

    // Category 2 - Formats By Type
    { id: 5, name: 'Hardback', categoryId: 2, typeId: 1 },
    { id: 6, name: 'Paperback', categoryId: 2, typeId: 1 },
    { id: 7, name: 'Digital', categoryId: 2, typeId: 1 },

    { id: 8, name: 'Hardback', categoryId: 2, typeId: 2 },
    { id: 9, name: 'Paperback', categoryId: 2, typeId: 2 },
    { id: 10, name: 'Digital', categoryId: 2, typeId: 2 },

    { id: 11, name: 'DVD', categoryId: 2, typeId: 3 },
    { id: 12, name: 'Blue-Ray', categoryId: 2, typeId: 3 },
    { id: 13, name: 'Digital', categoryId: 2, typeId: 3 },

    { id: 14, name: 'Computer', categoryId: 2, typeId: 4 },
    { id: 15, name: 'XBox', categoryId: 2, typeId: 4 },
    { id: 16, name: 'XBox 360', categoryId: 2, typeId: 4 },
    { id: 17, name: 'XBox One', categoryId: 2, typeId: 4 },
    { id: 18, name: 'Playstation', categoryId: 2, typeId: 4 },
    { id: 19, name: 'Playstation 2', categoryId: 2, typeId: 4 },
    { id: 20, name: 'Playstation 3', categoryId: 2, typeId: 4 },
    { id: 21, name: 'Playstation 4', categoryId: 2, typeId: 4 },
    { id: 22, name: 'Nintendo GameCube', categoryId: 2, typeId: 4 },
    { id: 23, name: 'Nintendo Wii', categoryId: 2, typeId: 4 },
    { id: 24, name: 'Nintendo Switch', categoryId: 2, typeId: 4 },
    { id: 25, name: 'Digital', categoryId: 2, typeId: 4 },

    // Category 3 - Genres
    { id: 26, name: 'Action and adventure', categoryId: 3, typeId: 1 },
    { id: 27, name: 'Art', categoryId: 3, typeId: 1 },
    { id: 28, name: 'Alternate history', categoryId: 3, typeId: 1 },
    { id: 29, name: 'Autobiography', categoryId: 3, typeId: 1 },
    { id: 30, name: 'Anthology', categoryId: 3, typeId: 1 },
    { id: 31, name: 'Biography', categoryId: 3, typeId: 1 },
    { id: 32, name: 'Chick lit', categoryId: 3, typeId: 1 },
    { id: 33, name: 'Book review', categoryId: 3, typeId: 1 },
    { id: 34, name: 'Children\'s literature', categoryId: 3, typeId: 1 },
    { id: 35, name: 'Cookbook', categoryId: 3, typeId: 1 },
    { id: 36, name: 'Comic book', categoryId: 3, typeId: 1 },
    { id: 37, name: 'Diary', categoryId: 3, typeId: 1 },
    { id: 38, name: 'Coming-of-age', categoryId: 3, typeId: 1 },
    { id: 39, name: 'Dictionary', categoryId: 3, typeId: 1 },
    { id: 40, name: 'Crime', categoryId: 3, typeId: 1 },
    { id: 41, name: 'Encyclopedia', categoryId: 3, typeId: 1 },
    { id: 42, name: 'Drama', categoryId: 3, typeId: 1 },
    { id: 43, name: 'Guide', categoryId: 3, typeId: 1 },
    { id: 44, name: 'Fairytale', categoryId: 3, typeId: 1 },
    { id: 45, name: 'Health', categoryId: 3, typeId: 1 },
    { id: 46, name: 'Fantasy', categoryId: 3, typeId: 1 },
    { id: 47, name: 'History', categoryId: 3, typeId: 1 },
    { id: 48, name: 'Graphic novel', categoryId: 3, typeId: 1 },
    { id: 49, name: 'Journal', categoryId: 3, typeId: 1 },
    { id: 50, name: 'Historical fiction', categoryId: 3, typeId: 1 },
    { id: 51, name: 'Math', categoryId: 3, typeId: 1 },
    { id: 52, name: 'Horror', categoryId: 3, typeId: 1 },
    { id: 53, name: 'Memoir', categoryId: 3, typeId: 1 },
    { id: 54, name: 'Mystery', categoryId: 3, typeId: 1 },
    { id: 55, name: 'Prayer', categoryId: 3, typeId: 1 },
    { id: 56, name: 'Paranormal romance', categoryId: 3, typeId: 1 },
    { id: 57, name: 'Religion, spirituality, and new age', categoryId: 3, typeId: 1 },
    { id: 58, name: 'Picture book', categoryId: 3, typeId: 1 },
    { id: 59, name: 'Textbook', categoryId: 3, typeId: 1 },
    { id: 60, name: 'Poetry', categoryId: 3, typeId: 1 },
    { id: 61, name: 'Review', categoryId: 3, typeId: 1 },
    { id: 62, name: 'Political thriller', categoryId: 3, typeId: 1 },
    { id: 63, name: 'Science', categoryId: 3, typeId: 1 },
    { id: 64, name: 'Romance', categoryId: 3, typeId: 1 },
    { id: 65, name: 'Self help', categoryId: 3, typeId: 1 },
    { id: 66, name: 'Satire', categoryId: 3, typeId: 1 },
    { id: 67, name: 'Travel', categoryId: 3, typeId: 1 },
    { id: 68, name: 'Science fiction', categoryId: 3, typeId: 1 },
    { id: 69, name: 'True crime', categoryId: 3, typeId: 1 },
    { id: 70, name: 'Short story', categoryId: 3, typeId: 1 },
    { id: 71, name: 'Suspense', categoryId: 3, typeId: 1 },
    { id: 72, name: 'Thriller', categoryId: 3, typeId: 1 },
    { id: 73, name: 'Young adult', categoryId: 3, typeId: 1 },

    { id: 74, name: 'Fantasy', categoryId: 3, typeId: 2 },
    { id: 75, name: 'Science Fiction', categoryId: 3, typeId: 2 },
    { id: 76, name: 'Space Opera', categoryId: 3, typeId: 2 },
    { id: 77, name: 'Postapocalyptic', categoryId: 3, typeId: 2 },
    { id: 78, name: 'Cyberpunk', categoryId: 3, typeId: 2 },
    { id: 79, name: 'Steampunk', categoryId: 3, typeId: 2 },
    { id: 80, name: 'Horror', categoryId: 3, typeId: 2 },

    { id: 81, name: 'Action', categoryId: 3, typeId: 3 },
    { id: 82, name: 'Adventure', categoryId: 3, typeId: 3 },
    { id: 83, name: 'Animation', categoryId: 3, typeId: 3 },
    { id: 84, name: 'Biography', categoryId: 3, typeId: 3 },
    { id: 85, name: 'Comedy', categoryId: 3, typeId: 3 },
    { id: 86, name: 'Crime', categoryId: 3, typeId: 3 },
    { id: 87, name: 'Documentary', categoryId: 3, typeId: 3 },
    { id: 88, name: 'Drama', categoryId: 3, typeId: 3 },
    { id: 89, name: 'Family', categoryId: 3, typeId: 3 },
    { id: 90, name: 'Fantasy', categoryId: 3, typeId: 3 },
    { id: 91, name: 'Film Noir', categoryId: 3, typeId: 3 },
    { id: 92, name: 'Game Show', categoryId: 3, typeId: 3 },
    { id: 93, name: 'History', categoryId: 3, typeId: 3 },
    { id: 94, name: 'Horror', categoryId: 3, typeId: 3 },
    { id: 95, name: 'Music', categoryId: 3, typeId: 3 },
    { id: 96, name: 'Musical', categoryId: 3, typeId: 3 },
    { id: 97, name: 'Mystery', categoryId: 3, typeId: 3 },
    { id: 98, name: 'News', categoryId: 3, typeId: 3 },
    { id: 99, name: 'Reality-TV', categoryId: 3, typeId: 3 },
    { id: 100, name: 'Romance', categoryId: 3, typeId: 3 },
    { id: 101, name: 'Sci-Fi', categoryId: 3, typeId: 3 },
    { id: 102, name: 'Short', categoryId: 3, typeId: 3 },
    { id: 103, name: 'Sport', categoryId: 3, typeId: 3 },
    { id: 104, name: 'Superhero', categoryId: 3, typeId: 3 },
    { id: 105, name: 'Talk Show', categoryId: 3, typeId: 3 },
    { id: 106, name: 'Thriller', categoryId: 3, typeId: 3 },
    { id: 107, name: 'War', categoryId: 3, typeId: 3 },
    { id: 108, name: 'Western', categoryId: 3, typeId: 3 },

    { id: 109, name: 'Action', categoryId: 3, typeId: 4 },
    { id: 110, name: 'Platform games', categoryId: 3, typeId: 4 },
    { id: 111, name: 'Shooter games', categoryId: 3, typeId: 4 },
    { id: 112, name: 'Fighting games', categoryId: 3, typeId: 4 },
    { id: 113, name: 'Beat \'em up games', categoryId: 3, typeId: 4 },
    { id: 114, name: 'Stealth game', categoryId: 3, typeId: 4 },
    { id: 115, name: 'Survival games', categoryId: 3, typeId: 4 },
    { id: 116, name: 'Rhythm games', categoryId: 3, typeId: 4 },
    { id: 117, name: 'Action-adventure', categoryId: 3, typeId: 4 },
    { id: 118, name: 'Survival horror', categoryId: 3, typeId: 4 },
    { id: 119, name: 'Metroidvania', categoryId: 3, typeId: 4 },
    { id: 120, name: 'Adventure', categoryId: 3, typeId: 4 },
    { id: 121, name: 'Text adventures', categoryId: 3, typeId: 4 },
    { id: 122, name: 'Graphic adventures', categoryId: 3, typeId: 4 },
    { id: 123, name: 'Visual novels', categoryId: 3, typeId: 4 },
    { id: 124, name: 'Interactive movie', categoryId: 3, typeId: 4 },
    { id: 125, name: 'Real-time 3D adventures', categoryId: 3, typeId: 4 },
    { id: 126, name: 'Role-playing', categoryId: 3, typeId: 4 },
    { id: 127, name: 'Action RPG', categoryId: 3, typeId: 4 },
    { id: 128, name: 'MMORPG', categoryId: 3, typeId: 4 },
    { id: 129, name: 'Roguelikes', categoryId: 3, typeId: 4 },
    { id: 130, name: 'Tactical RPG', categoryId: 3, typeId: 4 },
    { id: 131, name: 'Sandbox RPG', categoryId: 3, typeId: 4 },
    { id: 132, name: 'First-person party-based RPG', categoryId: 3, typeId: 4 },
    { id: 133, name: 'Cultural differences', categoryId: 3, typeId: 4 },
    { id: 134, name: 'Choices', categoryId: 3, typeId: 4 },
    { id: 135, name: 'Fantasy', categoryId: 3, typeId: 4 },
    { id: 136, name: 'Simulation', categoryId: 3, typeId: 4 },
    { id: 137, name: 'Construction and management simulation', categoryId: 3, typeId: 4 },
    { id: 138, name: 'Life simulation', categoryId: 3, typeId: 4 },
    { id: 139, name: 'Vehicle simulation', categoryId: 3, typeId: 4 },
    { id: 140, name: 'Strategy', categoryId: 3, typeId: 4 },
    { id: 141, name: '4X game', categoryId: 3, typeId: 4 },
    { id: 142, name: 'Artillery game', categoryId: 3, typeId: 4 },
    { id: 143, name: 'Real-time strategy (RTS)', categoryId: 3, typeId: 4 },
    { id: 144, name: 'Real-time tactics (RTT)', categoryId: 3, typeId: 4 },
    { id: 145, name: 'Multiplayer online battle arena (MOBA)', categoryId: 3, typeId: 4 },
    { id: 146, name: 'Tower defense', categoryId: 3, typeId: 4 },
    { id: 147, name: 'Turn-based strategy (TBS)', categoryId: 3, typeId: 4 },
    { id: 148, name: 'Turn-based tactics (TBT)', categoryId: 3, typeId: 4 },
    { id: 149, name: 'Wargame', categoryId: 3, typeId: 4 },
    { id: 150, name: 'Grand strategy wargame', categoryId: 3, typeId: 4 },
    { id: 151, name: 'Sports', categoryId: 3, typeId: 4 },
    { id: 152, name: 'Racing', categoryId: 3, typeId: 4 },
    { id: 153, name: 'Sports game', categoryId: 3, typeId: 4 },
    { id: 154, name: 'Competitive', categoryId: 3, typeId: 4 },
    { id: 155, name: 'Sports-based fighting', categoryId: 3, typeId: 4 },
    { id: 156, name: 'Other notable genres', categoryId: 3, typeId: 4 },
    { id: 157, name: 'MMO', categoryId: 3, typeId: 4 },
    { id: 158, name: 'Casual games', categoryId: 3, typeId: 4 },
    { id: 159, name: 'Party game', categoryId: 3, typeId: 4 },
    { id: 160, name: 'Programming game', categoryId: 3, typeId: 4 },
    { id: 161, name: 'Logic game', categoryId: 3, typeId: 4 },
    { id: 162, name: 'Trivia game', categoryId: 3, typeId: 4 },
    { id: 163, name: 'Board game or card game', categoryId: 3, typeId: 4 },

    // Category 4 - Status
    { id: 164, name: 'Wanted', categoryId: 4 },
    { id: 165, name: 'Owned', categoryId: 4 },
    { id: 166, name: 'On Loan', categoryId: 4 },
    { id: 167, name: 'Lost', categoryId: 4 },

    // Category 5 - Persons
    // Category 6 - Publishers
    // Category 7 - Setting
    // Category 8 - Series
    // Category 9 - Rulesets 
];